version: 0.2

env:
  variables:
    IMAGE_REPO_NAME: llamafactory-infer
    IMAGE_TAG: "0.9.4-dlc-mgpu"

phases:
  pre_build:
    commands:
      - set -eu
      - echo "AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION"
      - ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
      - REGION=${AWS_DEFAULT_REGION}
      - REPO_URI=${ACCOUNT_ID}.dkr.ecr.${REGION}.amazonaws.com/${IMAGE_REPO_NAME}
      - echo "REPO_URI=$REPO_URI"

      # Login to YOUR ECR (push target)
      - aws ecr get-login-password --region $REGION | docker login --username AWS --password-stdin ${ACCOUNT_ID}.dkr.ecr.${REGION}.amazonaws.com

      # Login to AWS Deep Learning Containers ECR (base image lives here)
      # Your base image URI is us-east-1, so keep this registry in us-east-1.
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 763104351884.dkr.ecr.us-east-1.amazonaws.com

      - echo "ECR logins OK"

  build:
    commands:
      # Build using the real Dockerfile name
      - docker build -f DOCKERFILE -t ${REPO_URI}:${IMAGE_TAG} .

  post_build:
    commands:
      - docker push ${REPO_URI}:${IMAGE_TAG}
      - printf '{"image_uri":"%s"}\n' ${REPO_URI}:${IMAGE_TAG} > image_detail.json
      - echo "Pushed ${REPO_URI}:${IMAGE_TAG}"

artifacts:
  files:
    - image_detail.json
