version: 0.2

env:
  variables:
    IMAGE_REPO_NAME: llamafactory-infer
    IMAGE_TAG: "0.9.4"

phases:
  pre_build:
    commands:
      - set -eu
      - echo "AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION"
      - ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
      - REGION=${AWS_DEFAULT_REGION}
      - REPO_URI=${ACCOUNT_ID}.dkr.ecr.${REGION}.amazonaws.com/${IMAGE_REPO_NAME}
      - echo "REPO_URI=$REPO_URI"
      - aws ecr get-login-password --region $REGION | docker login --username AWS --password-stdin ${ACCOUNT_ID}.dkr.ecr.${REGION}.amazonaws.com
      - echo "Logging in to Docker Hub..."
      - SECRET_JSON=$(aws secretsmanager get-secret-value --secret-id dockerhub/creds --query SecretString --output text)
      - DOCKERHUB_USERNAME=$(echo "$SECRET_JSON" | jq -r .username)
      - DOCKERHUB_TOKEN=$(echo "$SECRET_JSON" | jq -r .password)
      - echo "$DOCKERHUB_TOKEN" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
      - echo "Docker Hub login OK"

  build:
    commands:
      - docker build -f DOCKERFILE -t ${REPO_URI}:${IMAGE_TAG} .

  post_build:
    commands:
      - docker push ${REPO_URI}:${IMAGE_TAG}
      - printf '{"image_uri":"%s"}\n' ${REPO_URI}:${IMAGE_TAG} > image_detail.json
      - echo "Pushed ${REPO_URI}:${IMAGE_TAG}"

artifacts:
  files:
    - image_detail.json

